# Generated by Django 3.1.4 on 2020-12-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
